import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Info, Lock } from "lucide-react";
import { useDevice } from "../state/DeviceProvider";
import { AppShell } from "../components/AppShell";
import { Photo } from "../components/Media";
import { EvidenceToggle } from "../components/EvidenceToggle";
import { PasscodePrompt } from "../components/PasscodePrompt";
import type { MediaRef } from "../types";
const ACCENT = "#ffe9a8";
function Viewer({ items, startId }: { items: MediaRef[]; startId?: string }) {
  const [index, setIndex] = useState(Math.max(0, items.findIndex((x) => x.id === startId))); const media = items[index]; if (!media) return null;
  return <AppShell accent={ACCENT} title={media.takenAt ?? "Foto"} subtitle={`${index + 1} de ${items.length}`} padded={false} right={<Info size={18} className="text-[var(--inv-dim)]" />}><div className="relative flex flex-1 items-center justify-center bg-black/40"><div className="aspect-[3/4] w-full"><Photo media={media} rounded="rounded-none" /></div>{items.length > 1 && <><button type="button" onClick={() => setIndex((i) => (i - 1 + items.length) % items.length)} className="inv-press absolute left-1 flex h-11 w-11 items-center justify-center rounded-full bg-black/35" aria-label="Anterior"><ChevronLeft size={20} /></button><button type="button" onClick={() => setIndex((i) => (i + 1) % items.length)} className="inv-press absolute right-1 flex h-11 w-11 items-center justify-center rounded-full bg-black/35" aria-label="Próxima"><ChevronRight size={20} /></button></>}</div><div className="border-t border-[var(--inv-line)] px-4 py-4"><EvidenceToggle accent={ACCENT} item={{ id: `gallery:${media.id}`, appId: "gallery", title: media.caption ?? `Foto ${media.takenAt ?? ""}`, subtitle: media.place ? `Fotos · ${media.place}` : "Fotos", target: { app: "gallery", view: "photo", id: media.id } }} /></div></AppShell>;
}
export function GalleryApp() {
  const { caseData, current, open, isUnlocked } = useDevice();
  const all = useMemo(() => caseData.gallery.filter((g) => !g.lock || isUnlocked(`gallery:${g.id}`)).flatMap((g) => g.items), [caseData.gallery, isUnlocked]);
  if (current?.view === "photo") return <Viewer items={all} startId={current.id} />;
  if (current?.view === "album") { const group = caseData.gallery.find((g) => g.id === current.id); if (group) { const locked = Boolean(group.lock) && !isUnlocked(`gallery:${group.id}`); return <AppShell accent={ACCENT} title={group.label} subtitle={`${group.items.length} itens`} padded={false}>{locked && group.lock ? <PasscodePrompt unlockKey={`gallery:${group.id}`} lock={group.lock} accent={ACCENT} title="Álbum oculto" description="Este álbum está protegido por senha." /> : <div className="grid grid-cols-3 gap-[2px]">{group.items.map((m) => <button key={m.id} type="button" onClick={() => open({ app: "gallery", view: "photo", id: m.id })} className="aspect-square"><Photo media={m} rounded="rounded-none" /></button>)}</div>}</AppShell>; } }
  return <AppShell accent={ACCENT} title="Fotos" titleClassName="font-medium" subtitle={`${all.length} itens capturados`} padded={false}><div className="pb-6">{caseData.gallery.map((group) => { const locked = Boolean(group.lock) && !isUnlocked(`gallery:${group.id}`); return <section key={group.id}><div className="flex items-center justify-between px-4 pb-2 pt-5"><h3>{group.label}</h3><button type="button" onClick={() => open({ app: "gallery", view: "album", id: group.id })} className="inv-mono text-[10px] uppercase" style={{ color: ACCENT }}>{locked ? "Bloqueado" : "Ver tudo"}</button></div>{locked ? <button type="button" onClick={() => open({ app: "gallery", view: "album", id: group.id })} className="inv-press mx-4 flex w-[calc(100%-2rem)] items-center gap-3 rounded-xl border border-dashed px-4 py-6 text-left"><Lock size={16} style={{ color: ACCENT }} /><span className="text-[13px] text-[var(--inv-dim)]">{group.items.length} itens protegidos</span></button> : <div className="grid grid-cols-4 gap-[2px] px-[2px]">{group.items.map((m) => <button key={m.id} type="button" onClick={() => open({ app: "gallery", view: "photo", id: m.id })} className="inv-press aspect-square"><Photo media={m} rounded="rounded-none" /></button>)}</div>}</section>; })}</div></AppShell>;
}