import { useState } from "react";
import { MapPin, MessageCircle } from "lucide-react";
import { useDevice } from "../state/DeviceProvider";
import { AppShell } from "../components/AppShell";
import { Avatar, Photo } from "../components/Media";
import { EvidenceToggle } from "../components/EvidenceToggle";
import type { MatchProfile } from "../types";
const ACCENT = "#ff8e9e";
function Card({ profile }: { profile: MatchProfile }) { const { open } = useDevice(); return <button type="button" onClick={() => open({ app: "matches", view: "profile", id: profile.id })} className="inv-press relative aspect-[3/4] overflow-hidden rounded-2xl border text-left"><Photo media={profile.photos[0]} rounded="rounded-none" showKindBadge={false} /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/85 to-transparent px-3 pb-3 pt-8"><p>{profile.name}{!profile.redacted && <span className="text-[var(--inv-dim)]">, {profile.age}</span>}</p><p className="inv-mono flex items-center gap-1 text-[10px] text-[var(--inv-dim)]"><MapPin size={9} /> {profile.distanceKm} km</p></div>{profile.messages?.length ? <span className="absolute right-2 top-2 rounded-full p-1.5" style={{ background: ACCENT, color: "#2a0d14" }}><MessageCircle size={12} /></span> : null}</button>; }
function Detail({ profile }: { profile: MatchProfile }) { const [photo, setPhoto] = useState(0); const { messages = [] } = profile; return <AppShell accent={ACCENT} title={`${profile.name}${profile.redacted ? "" : `, ${profile.age}`}`} subtitle={profile.matchedAt ? `Match em ${profile.matchedAt}` : undefined} padded={false}><div className="relative aspect-[3/4] w-full"><Photo media={profile.photos[photo]} rounded="rounded-none" showKindBadge={false} />{profile.photos.length > 1 && <div className="absolute inset-x-4 top-3 flex gap-1.5">{profile.photos.map((p,i)=><button key={p.id} type="button" onClick={() => setPhoto(i)} className="h-[3px] flex-1 rounded-full" style={{ background: "#fff", opacity: i === photo ? .95 : .3 }} />)}</div>}</div><div className="px-5 py-5">{profile.city && <p className="inv-mono flex items-center gap-1.5 text-[11px] text-[var(--inv-dim)]"><MapPin size={11} /> {profile.city} · {profile.distanceKm} km</p>}{profile.bio && <p className="pt-3 text-[15px] leading-relaxed">{profile.bio}</p>}<div className="flex flex-wrap gap-2 pt-4">{profile.interests?.map((x)=><span key={x} className="rounded-full border px-3 py-1.5 text-[12px]" style={{ borderColor: `${ACCENT}55`, color: ACCENT }}>{x}</span>)}</div><div className="pt-5"><EvidenceToggle accent={ACCENT} item={{ id: `matches:${profile.id}`, appId: "matches", title: `Perfil — ${profile.name}`, subtitle: "Match", target: { app: "matches", view: "profile", id: profile.id } }} /></div>{messages.length > 0 && <div className="pt-7"><p className="inv-mono pb-3 text-[10px] uppercase text-[var(--inv-dim-2)]">Conversa</p>{messages.map((m)=><div key={m.id} className={`flex ${m.from === "victim" ? "justify-end" : "justify-start"} mb-2`}><div className="max-w-[80%] rounded-2xl px-3 py-2 text-[14px]" style={{ background: m.from === "victim" ? `${ACCENT}28` : "var(--inv-surface-2)" }}>{m.text}<span className="inv-mono block pt-1 text-right text-[9px] text-[var(--inv-dim-2)]">{m.at}</span></div></div>)}</div>}</div></AppShell>; }
export function MatchesApp() { const { caseData, current } = useDevice(); if (current?.view === "profile") { const p = caseData.matches.matches.find((x) => x.id === current.id); if (p) return <Detail profile={p} />; } const withChat = caseData.matches.matches.filter((x) => x.messages?.length); return <AppShell accent={ACCENT} title={<span className="inv-mono text-[16px] uppercase tracking-[.4em]">{caseData.matches.appName}</span>} padded={false} headerBackground="linear-gradient(180deg,rgba(180,59,87,.22),transparent)">{withChat.length > 0 && <div className="px-4 pt-4"><p className="inv-mono pb-3 text-[10px] uppercase text-[var(--inv-dim-2)]">Conversas</p><div className="flex gap-4 overflow-x-auto">{withChat.map((p)=><div key={p.id} className="flex w-[58px] flex-col items-center gap-1.5"><Avatar name={p.name} seed={p.photos[0]?.seed ?? p.id} size={52} ring /><span className="truncate text-[11px]">{p.name}</span></div>)}</div></div>}<div className="px-4 pb-6 pt-5"><p className="inv-mono pb-3 text-[10px] uppercase text-[var(--inv-dim-2)]">Matches</p><div className="grid grid-cols-2 gap-3">{caseData.matches.matches.map((p)=><Card key={p.id} profile={p} />)}</div></div></AppShell>; }