import { Archive, Ban, Link2, Search } from "lucide-react";
import { useEffect, useRef } from "react";
import { useDevice } from "../state/DeviceProvider";
import { AppShell } from "../components/AppShell";
import { Avatar, AudioPlayer, Photo } from "../components/Media";
import { EvidenceToggle } from "../components/EvidenceToggle";
import { PasscodePrompt } from "../components/PasscodePrompt";
import type { Conversation, Message } from "../types";
const ACCENT = "#7fd1a8";
function Bubble({ message, conversationId }: { message: Message; conversationId: string }) { const mine = message.from === "victim"; if (message.deleted) return <div className="flex justify-start"><div className="inv-mono flex items-center gap-2 rounded-2xl border border-dashed px-3 py-2 text-[11px] text-[var(--inv-dim-2)]"><Ban size={12} />Esta mensagem foi apagada</div></div>; return <div className={`group flex flex-col ${mine ? "items-end" : "items-start"}`}><div className="max-w-[78%] rounded-2xl px-3 py-2" style={{ background: mine ? "rgba(127,209,168,.14)" : "var(--inv-surface-2)" }}>{message.text && <p className="text-[14px] leading-snug">{message.text}</p>}{message.media && <div className="mt-1 h-44 w-[200px]"><Photo media={message.media} rounded="rounded-lg" /></div>}{message.audio && <AudioPlayer audio={message.audio} accent={ACCENT} />}{message.link && <a href={message.link.url} onClick={(e) => e.preventDefault()} className="mt-1 flex items-center gap-2 text-[12px]" style={{ color: ACCENT }}><Link2 size={13} />{message.link.label}</a>}<div className="inv-mono mt-1 text-right text-[9px] text-[var(--inv-dim-2)]">{message.at}</div></div><div className="mt-1 opacity-70"><EvidenceToggle compact accent={ACCENT} item={{ id: `messages:${conversationId}:${message.id}`, appId: "messages", title: message.text?.slice(0, 60) ?? (message.audio ? "Áudio" : "Mídia"), subtitle: `Mensagens · ${message.at}`, target: { app: "messages", view: "thread", id: conversationId } }} /></div></div>; }
function Thread({ conversation }: { conversation: Conversation }) { const { isUnlocked } = useDevice(); const end = useRef<HTMLDivElement>(null); const locked = Boolean(conversation.lock) && !isUnlocked(`messages:${conversation.id}`); useEffect(() => { if (!locked) end.current?.scrollIntoView({ block: "end" }); }, [locked]); return <AppShell accent={ACCENT} title={conversation.person.name} subtitle={conversation.archived ? "Conversa arquivada" : "online há 2 dias"} right={<Avatar name={conversation.person.name} seed={conversation.person.avatarSeed} size={32} />}>{locked && conversation.lock ? <PasscodePrompt unlockKey={`messages:${conversation.id}`} lock={conversation.lock} accent={ACCENT} title="Conversa arquivada" description="Esta conversa foi protegida." /> : <div className="flex flex-col gap-3 pb-2">{conversation.messages.map((m) => <div key={m.id}><Bubble message={m} conversationId={conversation.id} /></div>)}<div ref={end} /></div>}</AppShell>; }
export function MessagesApp() { const { caseData, current, open } = useDevice(); if (current?.view === "thread") { const c = caseData.messages.find((x) => x.id === current.id); if (c) return <Thread conversation={c} />; } const active = caseData.messages.filter((c) => !c.archived); const archived = caseData.messages.filter((c) => c.archived); return <AppShell accent={ACCENT} title="Mensagens" titleClassName="font-medium" right={<Search size={18} />} headerBackground="linear-gradient(180deg,rgba(31,107,74,.18),transparent)">{archived.length > 0 && <button type="button" onClick={() => open({ app: "messages", view: "thread", id: archived[0].id })} className="inv-press mb-1 flex w-full items-center gap-3 rounded-2xl px-2 py-3 text-left"><span className="flex h-[46px] w-[46px] items-center justify-center rounded-full border"><Archive size={18} /></span><span><p>Arquivadas</p><p className="text-[13px] text-[var(--inv-dim)]">{archived.length} conversa(s)</p></span></button>}<div>{active.map((c) => <button key={c.id} type="button" onClick={() => open({ app: "messages", view: "thread", id: c.id })} className="inv-press flex w-full items-center gap-3 rounded-2xl px-2 py-3 text-left"><Avatar name={c.person.name} seed={c.person.avatarSeed} size={46} /><div className="min-w-0 flex-1"><div className="flex justify-between"><span className="truncate">{c.person.name}</span><span className="inv-mono text-[10px] text-[var(--inv-dim-2)]">{c.time}</span></div><span className="truncate text-[13px] text-[var(--inv-dim)]">{c.preview}</span></div>{c.unread ? <span className="rounded-full px-2 text-[10px]" style={{ background: ACCENT, color: "#0b1a13" }}>{c.unread}</span> : null}</button>)}</div></AppShell>; }